// src/app/layout.tsx
import type { Metadata } from 'next' 
import './globals.css'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import StoreProvider from '@/providers/StoreProvider'
import NextAuthSessionProvider from "../providers/NextAuthSessionProvider"

export const metadata: Metadata = {
  title: 'The Car Edition Pro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=300, initial-scale=1, maximum-scale=1, user-scalable=no"/>
      </head>
      <NextAuthSessionProvider>
        <StoreProvider>
          <body
            className="font-rajdhani antialiased min-h-screen flex flex-col"
            suppressHydrationWarning={true}
          >
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </body>
        </StoreProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
